### ISSUE TITLE
Handle ReactComponentStylingFlavors enum in a nice way

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#185]
This enum is giving us a hard time when working with the generators in another TS project because we need to import it manually.

We have two options:
- we remove that in favor of regular strings
- we export it together with the component generator package and we make it so that it's easy to use in other projects using TS

**Comment by JayaKrishnaNamburu** [comment]
I feel this is also dependent on the lerna's adoption discussion, as I tried to adopt something like this in my fork 👇 
~~~
const { createReactComponentGenerator } = require('@teleporthq/teleport-react-component-generator');
const reactStyledJSXPlugin = require('@teleporthq/teleport-react-styled-jsx')

const generator = createReactComponentGenerator({ reactStyledJSXPlugin });
~~~
where we will be passing the plugin instead of a string when we split the code base into individual packages so we don't need to load all the plugins which were not being used by default, we can make ``inlineStyles`` by default and if the user passes some other plugin we adopt that, then we don't need to maintain this ``ReactComponentStylingFlavors`` enum.

Something like this --> https://github.com/JayaKrishnaNamburu/teleport-code-generators/blob/feature/lerna-setup/packages/teleport-react-component-generator/src/react-component.ts#L42
