### ISSUE TITLE
Component generator standard interface

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#27]
The component generators all expose an async function called `generateComponent`. This function runs the major parts of the component generator (resolver, assembly, builder) and returns a standard interface. This interface could be a bit better

**Current Implementation**
- `code` - `string` - the formatted main file (for react it's the .js file, for vue is the entire .vue file)
- `externalCSS` - `string` - any external css which the generator might compile (used only for `css-modules` at the moment)
- `dependencies` - `Record<string, string>` - all the external dependencies (of type: `package`) which are needed by the project generators for the `package.json`.

**Proposals**
- `code` and `externalCSS` can be exported as an array of `outputs`, with a file type or identifier next to them
- `code` can be exported as `componentCode` and `externalCSS` can be exported (together with other potential files) as an array of external files.
- `dependencies` could stay in the same way, but it could be `null` if no external dependencies are there. At the moment it is returning an empty object.

**Comment by JayaKrishnaNamburu** [comment]
Hey, @alexnm I would like to look into this, is this available?

**Comment by alexnm** [comment]
@JayaKrishnaNamburu it would help us better if you want to have a look at this, since you worked a bit with the Vue Plugin - https://github.com/teleporthq/teleport-code-generators/issues/96

**Comment by JayaKrishnaNamburu** [comment]
Sure, will look into that 👍

**Comment by alexpausan** [comment]
After the discussions had on this topic, I will take the first proposal made by @alexnm, with some adjustments. 

The component generator will return an array of `outputs` or maybe we'll call it `codeBlocks` which will contain all the **JS**, **HTML** and **CSS** blocks.

Regarding the **Vue** component generator, I will make an update so that it will return the blocks separately, now they're bundled into a single file, and the the project generator will take the decision regarding the way to group them or not. 

`externalDependencies` will become `dependencies` and will probably suffer further changes with the assets update.

**Comment by alexnm** [comment]
@alexpausan check out the project generators once we merge #115

**Comment by JayaKrishnaNamburu** [comment]
@alexpausan any update on this ?

**Comment by alexpausan** [comment]
yes, will make an update soon on this. 
Probably the output will be `codeOutputs` and `dependecies` and will have to update a bit according to #115

**Comment by vladnicula** [comment]
can we close this now? We merged the new interface in release/0.6
