### ISSUE TITLE
teleport-component-generator-vue malfunction?

### ISSUE THREAD

**Issue by anamariaoros** [teleporthq/teleport-code-generators#275]
teleport-component-generator-vue throws error: 
~~~
Expected node, not ` .... `
~~~

Reproducing scenario:
- use https://repl.teleporthq.io/
- enter the following UIDL sample:
~~~
{
  "name": "Static",
  "node": {
  	"type": "static",
	   "content":  ["Hello child"]
	 }
}
~~~
- check the difference between React and VUE component generators i.e. the React component generator provides component with string, the VUE compnent generator throws error 
~~~
generateReactComponent Error: Expected node, not `hello`
    at e.exports (index.js:1) .....
~~~
Note: the message **generateReactComponent** might be misguiding - it's the message inside the console.log.

Expected behavior:
- Both component generators should provide usable/code.

**Comment by JayaKrishnaNamburu** [comment]
We had the same issue with the **react generators** as well and we handled it here --> https://github.com/teleporthq/teleport-code-generators/pull/212

This is happening because we wrap the tags with a span in the case of an element. By in the case of static nodes we just send back the string which results in something like this

~~~
<template>
Hello World
</template>
~~~

which should be like this

~~~
<template>
<span>Hello World</span>
</tempalte>
~~~

Can I go ahead and follow the same approach that we did for **react-generators** ?

**Comment by alexnm** [comment]
as this is not release critical, I'm moving it to the official release so we can close the milestone and do a npm publish tomorrow
