### ISSUE TITLE
Extend validation to events

### ISSUE THREAD

**Issue by anamariaoros** [teleporthq/teleport-code-generators#277]
Validation should be extended to event defined in UIDL.
Currently it throws this error:
~~~
TypeError: Cannot read property 'type' of undefined
    at createStateChangeStatement (utils.js:251)
    at utils.js:47
    at Array.forEach (<anonymous>)
~~~

To reproduce:
- use https://repl.teleporthq.io/
- enter the uidl below:
~~~
{
  "name": "Simple Component",
  "node": {
    "type": "element",
    "content": {
      "elementType": "container",
      "children": [{
        "type": "element",
        "content": {
          "elementType": "button",
          "name": "openmodal",
          "children": [{
                  "type": "static",
                  "content": "Show Popup"
                }],
          "events": {
            "click": [{
            "type": "stateChange",
            "modifies": "isOpen",
            "newState": true
          }]
          },
          "attrs": { 
            "data-static-attr": {
              "type": "static",
              "content": "test"
            }
          },
          "attributes":{ 
            "htmlFor": {
             "type": "static",
              "content": "test"
            }
          }
        }
      }]
    }
  }
}
~~~
- check error in console

**Comment by chavda-bhavik** [comment]
Hii, I want to contribute to this. 

I get to know that this error occurred when using react, so I look into `packages/teleport-component-generator-react`, but couldn't able to find anything.

Can you say where to look for this issue?

**Comment by JayaKrishnaNamburu** [comment]
Hello @chavda-bhavik happy to have you here, UIDL is validated before passing for `code-generaion`. So, fix should happen in `teleporthq/teleport-udl-validator`. I will try to explain the issue here. 

- Here is an example which uses events - https://repl.teleporthq.io/?uidlLink=fa289c0f-f544-4fcf-ae48-b1e0f953596c&flavor=React&style=CSS-Modules
- So, for an event handler, right now we support only a state change. So, we need a valid `stateDefiniton` in the event handler.
-  modified the above UDL from the PR here - https://repl.teleporthq.io/?uidlLink=495dcf70-320f-472c-a20e-7031d1bd1722&flavor=React&style=CSS-Modules
- The bug here is, validator should throw error, when `isOpen` stateDefinition is not definied.
- You can check this https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-uidl-validator/src/validator/utils.ts#L160 as an example for this.

**Comment by chavda-bhavik** [comment]
Thank you @JayaKrishnaNamburu, I went through https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-uidl-validator/src/validator/utils.ts file and found that it has validation for dynamic content at https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-uidl-validator/src/validator/utils.ts#L144, but don't have validation that validates event state.

Do I need to add validation for the events that validate stateDefinition while encountered with events like stateChange?

**Comment by JayaKrishnaNamburu** [comment]
Yes, so while traversing through the UIDL here https://github.com/teleporthq/teleport-code-generators/blob/development/packages/teleport-uidl-validator/src/validator/utils.ts#L101

you can add checks for `node.type ==== 'element'` and if the element has `events` on it. If a node has events, then `event.modifies` should be present in `stateKeys`. If not throw an error 😄
