### ISSUE TITLE
Preact project does not use the generated index.html

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#342]
While testing out the preact project, I noticed that the roboto font and the title are not set in the running project. then I looked at the build task in preact and it is creating a new file, not using the existing one. In React this works, values set in index.html are preserved when running the app

**Comment by JayaKrishnaNamburu** [comment]
Yes, we can see more clearly with the title tag that we are assigning and the title tag that is being rendered

```
<title>Show-off for a few capabilities</title>
```

<img width="164" alt="Screenshot 2019-08-19 at 9 50 16 AM" src="https://user-images.githubusercontent.com/11075561/63239017-c5a6b380-c266-11e9-8e00-c9e53a246840.png">

**Comment by JayaKrishnaNamburu** [comment]
@alexnm so after looking after this, Here are the gotcha's

1. Preact won't expose its 'index.html` file. It has its templates stored under `preact-cli`
2. So, in the build phase. It will pick from the template instead of using the existing `index.html` file.
3. Any addition to the file, need to be done in the template file. So in build, the changes will reflect.


Possible solution
- Copy the default template to our `teleporthq/teleport-project-template-preact` and change the build script to ```preact build --template src/index.html```. But this should be done manually, because we can't inject tags in the existing file at the moment.

- Manually create the template file with a specific builder so we can generate a new template file and use it in the build phase.

```
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="utf-8">
		<title><%= htmlWebpackPlugin.options.title %></title>
		<meta name="viewport" content="width=device-width,initial-scale=1">
		<meta name="mobile-web-app-capable" content="yes">
		<meta name="apple-mobile-web-app-capable" content="yes">
		<link rel="manifest" href="<%= htmlWebpackPlugin.files.publicPath %>manifest.json">
		<% if (htmlWebpackPlugin.options.manifest.theme_color) { %>
			<meta name="theme-color" content="<%= htmlWebpackPlugin.options.manifest.theme_color %>">
		<% } %>
		<% for (var chunk of webpack.chunks) { %>
		 <% if (chunk.names.length === 1 && chunk.names[0] === 'polyfills') continue; %>
			<% for (var file of chunk.files) { %>
				<% if (htmlWebpackPlugin.options.preload && file.match(/\.(js|css)$/)) { %>
					<link rel="preload" href="<%= htmlWebpackPlugin.files.publicPath + file %>" as="<%= file.match(/\.css$/)?'style':'script' %>">
				<% } else if (file.match(/manifest\.json$/)) { %>
					<link rel="manifest" href="<%= htmlWebpackPlugin.files.publicPath + file %>">
				<% } %>
			<% } %>
		<% } %>
	</head>
	<body>
		<%= htmlWebpackPlugin.options.ssr({
			url: '/'
		}) %>
		<script defer src="<%= htmlWebpackPlugin.files.chunks['bundle'].entry %>"></script>
		<script>window.fetch||document.write('<script src="<%= htmlWebpackPlugin.files.chunks["polyfills"].entry %>"><\/script>')</script>
	</body>
</html>

```

Default template file ☝️
