### ISSUE TITLE
Investigate the preact codesandbox export

### ISSUE THREAD

**Issue by alexnm** [teleporthq/teleport-code-generators#367]
https://codesandbox.io/s/src6v

At first it seems that the error is caused by .babelrc, as babel.config.js doesn't throw an error. However, that still doesn't work as it outputs a blank screen.

Also, we might look into preact-helmet, it seems that react-helmet doesn't work with this setup without preact-compact.

However, locally the project builds just fine, so maybe it's a thing with preact-cli?

**Comment by JayaKrishnaNamburu** [comment]
Here is a working example with ``teleport-project-generator-preact`` --> https://codesandbox.io/s/teleportproject-qiyvs

Why it is not working with default setup?

1. I think, *.babelrc* file which we are packing with the repo is colliding with the codesandbox setup.
 - The solution will be, just removing the *.babelrc* file from the project while publishing to codesandbox.
2. In regular setup, on runnning `yarn start:development`. Preact will run a build with the *preact-build* command with the template that is passed with it. Then preact serves them with a local server.
 - The solution is, by following the pattern of preact's codesandbox way. Remove *.babelrc* file and then instead of exporting `App` from the `index.js`. Use `render` from `preact` and render it to the DOM body.

Steps:
1. Remove `.babelrc`
2. Change it to render instead of exporting the App in `index.js`
3. Remove index.html

These are the changes, needed for packing a project for codesandbox.
