### ISSUE TITLE
UIDL schema returns true even if name is missing

### ISSUE THREAD

**Issue by JayaKrishnaNamburu** [teleporthq/teleport-code-generators#91]
Currently, even if the ``name`` attribute is missing in the schema which is causing to run into improper code generation like shown in this [codesandbox](https://codesandbox.io/s/xv4q9p1jzw) example.

Current Behaviour
The UIDL validators return ``true`` even if the name is missing while defining ``states`` as it is defined in the schema

Solution
Need to check while the UIDL validators are returning true.

**Comment by JayaKrishnaNamburu** [comment]
I am fixing this in #89 but opened an issue just in case for any future reference.

**Comment by JayaKrishnaNamburu** [comment]
Sorry for messing around 😅 but this needs a bit investigation, please check the sandbox example as the ``name`` is already defined in the schema but the validator is returning true even if it is missing, maybe it should be defined as ``required``.

**Comment by alexnm** [comment]
I need to publish the documentation with the updated UIDL structure soon. Sorry for being a bit late with this. Here's the explanation:

`name` is optional because it is inferred from the `type` field. so if the user only sends the `type` like `"type": "container"`, name will be "container".

`name` exists in the UIDL because the creator of the UIDL can choose custom names for nodes.

There's an additional `key` node which generated in the resolver and is unique (ex: `container`, `container1`, `container2`. The uniqueness of the `key` is used for identifying the classes when generating css.

**Comment by JayaKrishnaNamburu** [comment]
Yeah @alexnm but there was a catch here if the type is state the expressions are being generated because the name ks not present, but it works exactly as you described if the type is container of something 👍, its like an edge case maybe 😇

**Comment by alexnm** [comment]
yes, that's the edge case, it should be solved with #41. it has to be a separate validation rule as conditional validation via JSON Schema looks tricky and maybe not that transparent. I will close this as the behavior will be explained in the doc
