### ISSUE TITLE
CSS Plugin Overwrites Existing Classes Instead of Merging with Generated Classes for UIDLElements

### ISSUE THREAD

**Issue by julia-alberici** [teleporthq/teleport-code-generators#927]
**Issue Description:**  
When a `UIDLElement` has both a `style` attribute and a `class` attribute, the CSS plugin currently replaces the `class` attribute with the class it generates to apply the styles. I believe the correct behavior should be to merge the existing classes with the new class created by the plugin.

The behavior I'm referring to is caused by this function in the Common plugin, which is called by the CSS plugin
![image](https://github.com/user-attachments/assets/b6650e61-28f2-4c69-ba01-e6fa8249ebf3)

**Proposed Fix:**  
I have a suggestion for how to address this issue. If you agree with this solution or believe this is indeed an issue, I can open a PR:  
![image](https://github.com/user-attachments/assets/b0937b33-471f-4acc-99f3-9fce673ce00c)

**Comment by JayaKrishnaNamburu** [comment]
Hi @Julia-Alberici thanks for reporting this, we added support for this type of use-cases using `component-referenced` styles in static nodes. Something like this

```json
"referencedStyles": {
    "static-class-name": {
      "type": "style-map",
      "content": {
        "mapType": "component-referenced",
        "content": "static-class-name"
      }
    }
  },
```

This will generate styles and appends the class name that is specified in the `component-referenced` too. The main reason we do this, is because generators are framework agnostic. Means, `react` needs it to be `className`, preact and other need it as `class` and some other frameworks like react-native which we had before had a completly need approach. So, you can define the class name that you need there using the above approach and it generated the code into.

```jsx
<div className="person-spotlight-container static-class-name">
      Hello, welcome to teleportHQ!
    </div>
```

Here is a complete component json if you are interested in trying the same

```json
{
  "name": "Sample",
  "propDefinitions": {},
  "node": {
    "type": "element",
    "content": {
      "elementType": "container",
      "style": {
        "width": "300px",
        "border": "1px solid #ccc",
        "padding": "10px",
        "margin": "5px"
      },
      "referencedStyles": {
        "static-class-name": {
          "type": "style-map",
          "content": {
            "mapType": "component-referenced",
            "content": "static-class-name"
          }
        }
      },
      "children": [
        "Hello, welcome to teleportHQ!"
      ]
    }
  }
}

```

Component

```jsx
import React from 'react'

import './sample.css'

const Sample = (props) => {
  return (
    <div className="person-spotlight-container static-class-name">
      Hello, welcome to teleportHQ!
    </div>
  )
}

export default Sample

```

**Comment by julia-alberici-korp** [comment]
Hi @JayaKrishnaNamburu, I see, tsm for the explanation!!

**Comment by julia-alberici** [comment]
Hi @JayaKrishnaNamburu, I see, tsm for the explanation!!

**Comment by JayaKrishnaNamburu** [comment]
No problem @Julia-Alberici , closing this now. Let me know if you need help with anything else 😄
